language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t dshap/react-portfolio -f Dockerfile.dev .

script:
  - docker run -e dshap/react-portfolio npm run test -- --coverage