version: '3'
services: 
  web:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"

    volumes: 
      #save docker container dependencys
      - /app/node_modules
      #curFolder:ContainerFolder
      - .:/app
  tests:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      #save docker container dependencys
      - /app/node_modules
      #curFolder:ContainerFolder
      - .:/app
    command: ["npm", "run", "test"]
    